# Generated by Django 4.2.1 on 2023-05-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0003_alter_subject_name_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='lm.subject'),
        ),
    ]
