# Generated by Django 4.2.1 on 2023-05-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0004_remove_course_subject_course_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='lessons',
            field=models.ManyToManyField(to='lm.lesson'),
        ),
    ]
