# Generated by Django 4.2.1 on 2023-05-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0006_homework_student_teacher_delete_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
