# Generated by Django 4.2.1 on 2023-05-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0009_alter_homeworkgrade_grade_alter_userprofile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
