# Generated by Django 4.2.1 on 2023-05-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lm', '0010_remove_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lm.subject'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lm.teacher'),
        ),
    ]
